language: python
python:
  - "3.9"
  - "3.6"
  - "3.5"
  - "pypy3"
  - "2.7"
sudo: false
env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=3.0
before_install:
  - pip install httpretty mock coverage codecov
  - pip install -q django==$DJANGO_VERSION
install:
  - python setup.py develop
script:
  - python setup.py test
after_success:
  - codecov --env DJANGO_VERSION
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION=2.0
    - python: "2.7"
      env: DJANGO_VERSION=2.1
    - python: "2.7"
      env: DJANGO_VERSION=3.0
    - python: "pypy"
      env: DJANGO_VERSION=2.1
    - python: "3.5"
      env: DJANGO_VERSION=3.0
